# IMPORT STATEMENTS COMMENT
# Import multiprocessing to create and manage separate processes
# Provides Process class, current_process() function, and process naming capabilities
import multiprocessing

# Import time module to add delays/sleep intervals
# Used to simulate work and make process execution time visible
import time

# FUNCTION: myFunc
# Purpose: Demonstrates process identification and lifecycle
# Each process running this function will print its name before and after sleeping
def myFunc():
    # Get the current process object and extract its name
    # current_process() returns the Process object for the currently running process
    # .name returns the process name (either custom-set or auto-generated)
    # Examples: 'myFunc process' (custom) or 'Process-1' (default)
    name = multiprocessing.current_process().name
    
    # Print message showing this process has started, including its name
    # \n adds a newline for better formatting
    print("Starting process name = %s \n" % name)
    
    # Pause execution for 3 seconds
    # This simulates doing actual work and makes the process "sleep"
    # During this time, other processes can run (context switching)
    time.sleep(3)
    
    # Print message showing this process is exiting, including its name
    # This confirms the process completed its work successfully
    print("Exiting process name = %s \n" % name)

# MAIN EXECUTION BLOCK
# This code only runs when script is executed directly (not imported as module)
if __name__ == '__main__':
    
    # Create a Process with a CUSTOM name
    # name='myFunc process' - explicitly sets a human-readable name
    # target=myFunc - the function this process will execute
    # This process will be identifiable by its custom name
    process_with_name = multiprocessing.Process(
                        name='myFunc process',  # Custom name for identification
                        target=myFunc)          # Function to execute
    
    # DAEMON OPTION (commented out)
    # If uncommented, this would make the process a daemon
    # Daemon processes:
    #   - Automatically terminate when main program exits
    #   - Cannot create child processes
    #   - Are killed immediately without cleanup
    #   - Useful for background tasks that should not block program exit
    # process_with_name.daemon = True
    
    # Create a Process with DEFAULT name
    # No name parameter provided - Python will auto-generate a name
    # Default naming pattern: 'Process-1', 'Process-2', 'Process-3', etc.
    # This demonstrates the difference between custom and auto-generated names
    process_with_default_name = multiprocessing.Process(
                                target=myFunc)  # Same function, auto-named
    
    # Start the custom-named process
    # This creates a new system process and begins executing myFunc()
    # The process will print its custom name: "myFunc process"
    process_with_name.start()
    
    # Start the default-named process
    # This creates ANOTHER new system process running myFunc()
    # The process will print its auto-generated name: "Process-1" (or similar)
    process_with_default_name.start()
    
    # Wait for the custom-named process to complete
    # join() blocks the main program until this process finishes its work
    # Without this, main program might exit before processes complete
    process_with_name.join()
    
    # Wait for the default-named process to complete
    # Ensures both processes finish before main program ends
    # The main program will wait here until the second process also finishes
    process_with_default_name.join()
    
    # When both joins complete, main program exits
    # Total execution time: ~3 seconds (both processes run in parallel)



#     Process Creation Comparison:
# Process	                   Name Type	      Name Value        	How it's identified
# process_with_name 	         Custom	     'myFunc process'	      Explicitly set by programmer
# process_with_default_name 	 Default	  'Process-1'         	Auto-generated by Python

# Main Process (Parent)
#     │
#     ├─ Creates process_with_name (custom name: 'myFunc process')
#     ├─ Creates process_with_default_name (auto name: 'Process-1')
#     │
#     ├─ process_with_name.start() ──────────┐
#     │                                      │
#     ├─ process_with_default_name.start() ──┤
#     │                                      │
#     │                    ┌─────────────────┴─────────────────┐
#     │                    │                                   │
#     │              [PROCESS 1]                         [PROCESS 2]
#     │              Name: 'myFunc process'              Name: 'Process-1'
#     │                    │                                   │
#     │              Prints: "Starting process                Prints: "Starting process
#     │              name = myFunc process"                   name = Process-1"
#     │                    │                                   │
#     │              Sleeps 3 seconds                    Sleeps 3 seconds
#     │              (parallel execution)                (parallel execution)
#     │                    │                                   │
#     │              Prints: "Exiting process                 Prints: "Exiting process
#     │              name = myFunc process"                   name = Process-1"
#     │                    │                                   │
#     └─ process_with_name.join() ←───────────────────────────┘
#     └─ process_with_default_name.join() ←────────────────────┘


# output

# Starting process name = myFunc process 

# Starting process name = Process-2 

# Exiting process name = myFunc process 

# Exiting process name = Process-2


