# Import all functions from do_something.py (contains the random list generator)
from do_something import *
# Import time module to measure execution time
import time
# Import multiprocessing module to run tasks in an parallel manner
import multiprocessing

# Ensure this code runs only when executed directly (not imported)
if __name__ == "__main__":
     # here we start recording time to measure execution duration
    start_time = time.time()
    # Number of random numbers each process will generate
    size = 10000000 
     # Number of parallel processes to run  
    procs = 10 
     # We will store all process objects here so we can start and join them later. 
    jobs = []
    # now we are creating multiple processes
    for i in range(0, procs):
         # Each process has its own separate list
        out_list = list()
         # Create a new process running do_something with arguments size and out_list
        process = multiprocessing.Process\
                  (target=do_something,args=(size,out_list))
        # Add the process to the jobs list
        jobs.append(process)
 # Start all processes one by one
    for j in jobs:
        # Tells Python to actually run the process.
        j.start()
#After this, all 10 processes are running at the same time, generating 10 million random numbers each.
    for j in jobs:
        # Waits for all the process to finish before moving on.
        j.join()
#Shows that all random numbers have been generated by all processes.
    print ("List processing complete.")
    # Get the current time after finishing.
    end_time = time.time()
    # subtract end tome with start time to get runtime duration and print.
    print("multiprocesses time=", end_time - start_time)



# 10 processes will start at the same time.
# Each process will  10 million random numbers independently.
# The main program will  wait for all processes to finish and print acknowledgement along with runtme


#since we used 10 processes, the total time < running the same task 10 times one by one.
#This shows parallel computing  as instead of waiting for one big task to finish,
#  Python does many tasks at the same time

# output
# List processing complete.
# multiprocesses time= 4.500985383987427